`timescale 1ns / 1ps
`include "bf16_test_utils.svh"

// Uses the REAL, full-size ROM (rtl/projection/rope_sin_rom.mem /
// rope_cos_rom.mem, generated by scripts/gen_rope_rom.py) so this exercises
// the actual ROM content the design will ship with, not a synthetic stand-in.
//
// Two checks:
//   1. pos = 0 -> theta = 0 for every pair -> rotation is the identity
//      (y == x exactly, no bf16 rounding involved). This alone proves the
//      ROM loads, the handshakes work, and the rotate-half pairing/indexing
//      is wired the way the module intends.
//   2. pos = 4, pair 0 (highest frequency, freq = 1 so theta = pos exactly)
//      -> compared against $sin/$cos computed in the testbench, with a
//      tolerance that accounts for bf16 truncation across mul+add.
//
// NOTE: this does not replace a real golden-model (Python/NumPy) numerical
// verification pass across many positions - that is still open work, see
// the team's own "golden model" test plan.
module tb_rope;

    localparam int DATA_WIDTH = 16;
    localparam int D_MODEL = 64;
    localparam int MAX_POS = 512;
    localparam int PAIR_CNT = D_MODEL/2;

    logic clk_i = 0, rst_ni = 0;
    logic [$clog2(MAX_POS)-1:0] pos_i;
    logic [DATA_WIDTH:0] x_data_i;
    logic x_valid_i, x_last_i;
    logic x_ready_o;
    logic [DATA_WIDTH:0] y_data_o;
    logic y_valid_o, y_last_o;
    logic y_ready_i;

    real y_mem_real [0:D_MODEL-1];
    int errors = 0;
    int drain_cnt;

    rope #(.DATA_WIDTH(DATA_WIDTH), .D_MODEL(D_MODEL), .MAX_POS(MAX_POS)) dut (
        .clk_i(clk_i), .rst_ni(rst_ni),
        .pos_i(pos_i),
        .x_data_i(x_data_i), .x_valid_i(x_valid_i), .x_last_i(x_last_i), .x_ready_o(x_ready_o),
        .y_data_o(y_data_o), .y_valid_o(y_valid_o), .y_last_o(y_last_o), .y_ready_i(y_ready_i)
    );

    always #5 clk_i = ~clk_i;

    task automatic run_vector(input int pos, input real x_vec [0:D_MODEL-1]);
        begin
            pos_i = pos[$clog2(MAX_POS)-1:0];
            for (int m = 0; m < D_MODEL; m++) begin
                wait (x_ready_o == 1'b1);
                x_data_i = {1'b0, real_to_bf16(x_vec[m])};
                x_valid_i = 1'b1;
                x_last_i = (m == D_MODEL-1);
                @(posedge clk_i);
            end
            x_valid_i = 1'b0;
            x_last_i = 1'b0;

            drain_cnt = 0;
            while (drain_cnt < D_MODEL) begin
                @(posedge clk_i);
                if (y_valid_o) begin
                    y_mem_real[drain_cnt] = bf16_to_real(y_data_o[DATA_WIDTH-1:0]);
                    drain_cnt++;
                end
            end
        end
    endtask

    initial begin
        real x_all_ones [0:D_MODEL-1];
        real x_ramp [0:D_MODEL-1];
        real expected, tol;

        for (int i = 0; i < D_MODEL; i++) x_all_ones[i] = 1.0;
        for (int i = 0; i < D_MODEL; i++) x_ramp[i] = 1.0;

        rst_ni = 0;
        x_valid_i = 0; x_last_i = 0; x_data_i = '0; y_ready_i = 1; pos_i = '0;
        repeat (3) @(posedge clk_i);
        rst_ni = 1;
        @(posedge clk_i);

        // Check 1: pos = 0 -> identity rotation
        run_vector(0, x_all_ones);
        for (int i = 0; i < D_MODEL; i++) begin
            if (y_mem_real[i] != 1.0) begin
                errors++;
                $display("FAIL pos=0 y[%0d]: expected 1.0 got %0f", i, y_mem_real[i]);
            end
        end
        $display("pos=0 identity check done (%0s)", (errors == 0) ? "ok so far" : "FAILED");

        // Check 2: pos = 4, pair 0 (freq = 1, theta = 4.0 rad exactly)
        run_vector(4, x_ramp);
        tol = 0.08; // bf16 truncation across 2 muls + 1 add, generous margin
        expected = $cos(4.0) - $sin(4.0); // y1 for pair 0 = x1*cos - x2*sin, x1=x2=1
        if (!(y_mem_real[0] > expected - tol && y_mem_real[0] < expected + tol)) begin
            errors++;
            $display("FAIL pos=4 y1(pair0): expected ~%0f got %0f", expected, y_mem_real[0]);
        end else begin
            $display("PASS pos=4 y1(pair0): expected ~%0f got %0f", expected, y_mem_real[0]);
        end

        expected = $sin(4.0) + $cos(4.0); // y2 for pair 0 = x1*sin + x2*cos
        if (!(y_mem_real[PAIR_CNT] > expected - tol && y_mem_real[PAIR_CNT] < expected + tol)) begin
            errors++;
            $display("FAIL pos=4 y2(pair0): expected ~%0f got %0f", expected, y_mem_real[PAIR_CNT]);
        end else begin
            $display("PASS pos=4 y2(pair0): expected ~%0f got %0f", expected, y_mem_real[PAIR_CNT]);
        end

        if (errors == 0) $display("TB_ROPE: PASS");
        else $display("TB_ROPE: FAIL (%0d errors)", errors);
        $finish;
    end

    initial begin
        #2000000;
        $display("TB_ROPE: TIMEOUT");
        $finish;
    end

endmodule
